packages:
  - apps/*
  - packages/*

catalog:
  '@sveltejs/adapter-vercel': 6.3.0
  '@sveltejs/kit': ~2.50.0
  '@sveltejs/vite-plugin-svelte': ~6.2.4
  '@vercel/edge-config': ~1.4.3
  '@vercel/functions': ~3.3.6
  '@vercel/otel': ~2.1.0
  svelte: ^5.45.8
  svelte-check: ~4.3.4
  sveltekit-superforms: 2.27.1
  typescript: ~5.9.3
  vite: ~6.3.7
  zod: 3.25.76

onlyBuiltDependencies:
  - esbuild
